name: Deploy to EC2 (test branch)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          cat > .env <<EOF
          PORT=${{ secrets.PORT }}
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          EMAIL_FROM=${{ secrets.EMAIL_FROM }}
          EMAIL_TO=${{ secrets.EMAIL_TO }}
          EOF

      - name: Copy project and .env to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env,server.js,package.json,Dockerfile"
          target: "/home/ec2-user/api-mail"

      - name: Run Docker on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/api-mail
            sudo docker stop api-mail-container || true
            sudo docker rm   api-mail-container || true
            sudo docker build -t api-mail .
            sudo docker run -d \
              --name api-mail-container \
              -p 3002:3002 \
              --env-file .env \
              api-mail
